### ISSUE TITLE
java.lang.NullPointerException occuring during rebase.

### ISSUE THREAD

**Issue by PsiOmegaDelta** [atlantiscze/JMerge#1]
Exception occurs when attempting to rebase https://github.com/Baystation12/Baystation12/pull/18059/commits/a4ce8a5dcff484a2d9e50647fdc96eec4a3af5b1 on top of https://github.com/Baystation12/Baystation12/commit/7983c865b41a704a953679ac5c341469db6caf78

```
First, rewinding head to replay your work on top of it...
Applying: Adds paper bins to the mess hall and lounge, and a game vending machine to the mess (replacing a stool).
Using index info to reconstruct a base tree...
M	maps/torch/torch-2.dmm
Falling back to patching base and 3-way merge...
JMerge 1.4
Running with parameters:
-merge
.merge_file_a11212
.merge_file_b11212
.merge_file_c11212
.merge_file_b11212
CONFLICT: [66, 92, 0]
A conflict has been detected. Please specify which version should be used (local/remote/origin/abort):
Exception in thread "main" java.lang.NullPointerException
	at JMerge.JMerge.getResolveMode(JMerge.java:150)
	at JMerge.JMerge.merge(JMerge.java:95)
	at JMerge.JMerge.main(JMerge.java:31)
Unable to automatically resolve map conflicts, please merge manually.
Auto-merging maps/torch/torch-2.dmm
CONFLICT (content): Merge conflict in maps/torch/torch-2.dmm
error: Failed to merge in the changes.
Patch failed at 0001 Adds paper bins to the mess hall and lounge, and a game vending machine to the mess (replacing a stool).
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Done
```

**Comment by atlantiscze** [comment]
Resolved in new version
